version: '3.8'

networks:
  local-net:
    name: ${LOCAL_NETWORK}
    driver: bridge

services:

  superset:
    image: apache/superset
    container_name: ${COMPOSE_PROJECT_NAME}-apache-superset
    profiles: [ all, superset ]
    restart: ${RESTART_POLICY}
    networks:
      - local-net
    ports:
      - '8080:8088'
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    command: >
      bash -c "
      superset run -h 0.0.0.0 -p 8088 & sleep 10 &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset db upgrade &&
      superset load_examples &&
      superset init"

  chat-gpt:
    # image: openai:gpt
    image: openai:chat-gpt
    container_name: ${COMPOSE_PROJECT_NAME}-chat-gpt
    profiles: [ all, openai, chat-gpt ]
    restart: ${RESTART_POLICY}
    networks:
      - local-net
    ports:
      - 8085:8080
    environment:
      NODE_ENV: prod
      OPENAI_API_KEY: ${OPENAI_CHAT_GPT_API_KEY}
      PORT: 8080
      PAYLOAD_CAP: 1mb
