services:
  chat:
    image: ${OPEN_WEBUI_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-open-webui
    
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
      - ./vol/open-webui:/app/backend/data
    networks:
      - net
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}