version: "3.8"

networks:
  net:
    name: dev
    external: true

services:
  chat-gpt:
    image: ${OPENAI_CHAT_GPT_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-chat-gpt
    profiles: [all, gpt ]
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    # ports:
    #   - ${OPENAI_CHAT_GPT_PORT}:80
    environment:
      NODE_ENV: prod
      OPENAI_API_KEY: ${OPENAI_CHAT_GPT_API_KEY}
      PORT: 80
      PAYLOAD_CAP: 1mb

  file-tray:
    image: ${FILE_TRAY_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-file-tray
    profiles: [all, ft]
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${FILE_TRAY_PORT}:80
    environment:
      PORT: 80

  actual:
    image: ${ACTUAL_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-actual
    profiles: [all, actual]
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
      - ./vol/actual:/data
    networks:
      - net
    ports:
      - ${ACTUAL_PORT}:5006
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.

  i-spy:
    image: ${i_SPY_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-i-spy
    profiles: [all, i-spy]
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
      - ./vol/actual:/data
      - ./vol/i-spy/config/:/AgentDVR/Media/XML/
      - ./vol/i-spy/media/:/AgentDVR/Media/WebServerRoot/Media/
      - ./vol/i-spy/commands:/AgentDVR/Commands/
    networks:
      - net
    ports:
      - "${I_SPY_PORT}:8090"
      - "3478:3478/udp"
      - "50000-50010:50000-50010/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata

  jellyfin:
    image: ${JELLYFIN_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-jellyfin
    profiles: [all, jf]
    restart: ${COMPOSE_RESTART_POLICY}
    # user: uid:gid
    # network_mode: 'host'
    volumes:
      - ./vol/jf/media:/media
      - ./vol/jf/media2:/media2:ro
      # - /path/to/config:/config
      # - /path/to/cache:/cache
    networks:
      - net
    ports:
      - ${JELLYFIN_PORT}:8096
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
