include:
  - chat.app.service.yaml
  - file-tray.app.service.yaml
  - actual.app.service.yaml
  - i-spy.app.service.yaml
  - jellyfin.app.service.yaml
  - s-pdf.app.service.yaml
  - maybe.app.service.yaml

networks:
  net:
    name: dev
    external: true
