version: "3.8"

networks:
  net:
    name: ${COMPOSE_NETWORK}
    driver: bridge

services:
  chat-gpt:
    image: ${OPENAI_CHAT_GPT_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-chat-gpt
    profiles: [all, gpt ]
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    # ports:
    #   - ${OPENAI_CHAT_GPT_PORT}:80
    environment:
      NODE_ENV: prod
      OPENAI_API_KEY: ${OPENAI_CHAT_GPT_API_KEY}
      PORT: 80
      PAYLOAD_CAP: 1mb

  file-tray:
    image: ${FILE_TRAY_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-file-tray
    profiles: [all, ft]
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${FILE_TRAY_PORT}:80
    environment:
      PORT: 80