include:
  - compose/chat.app.service.yaml
  - compose/file-tray.app.service.yaml
  - compose/actual.app.service.yaml
  - compose/i-spy.app.service.yaml
  - compose/jellyfin.app.service.yaml
  - compose/s-pdf.app.service.yaml
  - compose/maybe.app.service.yaml

networks:
  net:
    name: dev
    external: true
