services:
  mongo-express:
    image: ${MONGO_EXPRESS_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-mongo_express
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    depends_on:
      - mongo