services:
  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-pgadmin
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}  # replace with your admin email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} # replace with your admin password
    volumes:
      - pgadmin:/var/lib/pgadmin