services:
  phpmyadmin:
    image: ${PHP_MY_ADMIN_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-phpmyadmin
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1G
      - PMA_HOSTS=mysql
    depends_on:
      - mysql