services:
  s-pdf:
    image: ${STIRLING_PDF_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-s-pdf
    
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
      - ../vol/s-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ../vol/s-pdf/extraConfigs:/configs
      - ../vol/s-pdf/customFiles:/customFiles/
      - ../vol/s-pdf/logs:/logs/
    networks:
      - net
    ports:
      - ${STIRLING_PDF_PORT}:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false