services:
  portainer-agent:
    image: ${PORTAINER_AGENT_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-portainer-agent
    
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
        - /var/lib/docker/volumes:/var/lib/docker/volumes
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    ports:
      - ${PORTAINER_AGENT_PORT}:9001