include:
  - compose/nginx-proxy.manager.service.yaml
  - compose/portainer.manager.service.yaml
  - compose/portainer-agent.manager.service.yaml
  - compose/uptime-kuma.manager.service.yaml
  - compose/syncthing.manager.service.yaml
  - compose/watchtower.manager.service.yaml

networks:
  net:
    name: dev
    external: true
