networks:
  net:
    name: dev
    external: true

services:
  nginx-proxy:
    image: ${NGINX_PROXY_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-nginx-proxy
    profiles: [ all, nginx-proxy ]
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
      - ./vol/nginx-proxy/data:/data
      - ./vol/nginx-proxy/letsencrypt:/etc/letsencrypt
    networks:
      - net
    ports:
      - 80:80
      - ${NGINX_PROXY_DASHBOARD_PORT}:81
      - 443:443

  portainer:
    image: ${PORTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-portainer
    profiles: [ all, portainer ]
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
        - ./vol/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    ports:
      - ${PORTAINER_HTTPS_PORT}:9443
      # - ${PORTAINER_HTTP_PORT}:8000

  portainer-agent:
    image: ${PORTAINER_AGENT_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-portainer-agent
    profiles: [ all, portainer-agent ]
    restart: ${COMPOSE_RESTART_POLICY}
    volumes:
        - /var/lib/docker/volumes:/var/lib/docker/volumes
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    ports:
      - ${PORTAINER_AGENT_PORT}:9001
