include:
  - nginx-proxy.manager.service.yaml
  - portainer.manager.service.yaml
  - portainer-agent.manager.service.yaml
  - uptime-kuma.manager.service.yaml
  - syncthing.manager.service.yaml
  - watchtower.manager.service.yaml

networks:
  net:
    name: dev
    external: true
