services:
  adminer:
    image: ${ADMINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-adminer
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_UPLOAD_LIMIT=1G
    labels:
      - com.centurylinklabs.watchtower.enable=true