services:
  clickhouse-client:
    image: ghcr.io/caioricciuti/ch-ui:latest  # Using the ClickHouse UI client image here
    container_name: ${COMPOSE_PROJECT_PREFIX}-clickhouse-client
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - 5521:5521
    # environment:
      # VITE_CLICKHOUSE_URL: http://dev-clickhose:8123  # Adjust based on network if needed
      # VITE_CLICKHOUSE_URL: http://dev-clickhose:9000  # Adjust based on network if needed
      # VITE_CLICKHOUSE_USER: root
      # VITE_CLICKHOUSE_PASS: pass123