include:
  - redis.storage.service.yaml
  - redis-commander.storage.service.yaml
  - mysql.storage.service.yaml
  - phpmyadmin.storage.service.yaml
  - mongo.storage.service.yaml
  - mongo-express.storage.service.yaml
  - psql.storage.service.yaml
  - adminer.storage.service.yaml
  - pgadmin.storage.service.yaml
  - couchdb.storage.service.yaml
  - clickhouse.storage.service.yaml
  - clickhouse-client.storage.service.yaml
  - hasura.storage.service.yaml

networks:
  net:
    name: dev
    external: true

volumes:
  mysql:
    name: dev-mysql
  pgadmin:
    name: dev-pgadmin
