include:
  - compose/redis.storage.service.yaml
  - compose/redis-commander.storage.service.yaml
  - compose/mysql.storage.service.yaml
  - compose/phpmyadmin.storage.service.yaml
  - compose/mongo.storage.service.yaml
  - compose/mongo-express.storage.service.yaml
  - compose/psql.storage.service.yaml
  - compose/adminer.storage.service.yaml
  - compose/pgadmin.storage.service.yaml
  - compose/couchdb.storage.service.yaml
  - compose/clickhouse.storage.service.yaml
  - compose/clickhouse-client.storage.service.yaml
  - compose/hasura.storage.service.yaml

networks:
  net:
    name: dev
    external: true

volumes:
  mysql:
    name: dev-mysql
  pgadmin:
    name: dev-pgadmin
