services:
  hasura:
    image: ${HASURA_IMAGE}
    container_name: ${COMPOSE_PROJECT_PREFIX}-hasura
    
    restart: ${COMPOSE_RESTART_POLICY}
    networks:
      - net
    ports:
      - ${HASURA_PORT}:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}